README.md, deployments/k3d/README.md
- add documentation for using the published k3d image and K8s artifacts
=> document how to quickly get started with a local cluster

containerd-shim-spin-v1/Cargo.lock, containerd-shim-spin-v1/Cargo.toml, containerd-shim-spin-v1/src/loader.rs, containerd-shim-spin-v1/src/main.rs, containerd-shim-spin-v1/src/podio.rs, images/spin/Cargo.toml, images/spin/src/lib.rs
=> feat:: updated spin to the latest commit

deployments/workloads/slight/workload.yaml
=> feat: changed docker to ghcr

.github/workflows/build.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml, containerd-shim-slight-v1/src/main.rs, deployments/k3d/Makefile
=> feat: added arm64 build

.github/workflows/build.yaml, .github/workflows/release.yaml
=> feat: convert cache to rust-cache

images/spin_dotnet/Dockerfile, images/spin_dotnet/Handler.cs, images/spin_dotnet/Project.csproj, images/spin_dotnet/spin.toml
Added a dotnet Spin application following the steps described in this article: https://www.fermyon.com/blog/webassembly-for-dotnet-developers-spin-sdk-intro. 
=> feat: added spin dotnet image

containerd-shim-spin-v1/quickstart.md
=> docs: add quickstart for spin application

containerd-shim-spin-v1/quickstart.md
=> docs: add echo clarifying reason for sleep

containerd-shim-slight-v1/quickstart.md
=> docs: add SpiderLightning quickstart

.github/workflows/build.yaml
=> removed bin

containerd-shim-slight-v1/quickstart.md
=> docs: fixed missing command to add wasm32-wasi target

deployments/k3d/README.md
=> fix(docs): updaed k3d README to point to the latest workloads

.github/workflows/release.yaml, Makefile, images/slight/Dockerfile, images/spin/Dockerfile, images/spin_dotnet/Dockerfile
=> feat: changed workload image arch to wasi/wasm

containerd-shim-slight-v1/quickstart.md, containerd-shim-spin-v1/quickstart.md, deployments/k3d/README.md
Moved from latest tag to v0.3.2 in k3d image.
=> docs: changed from latest to v0.3.2 tag for k3d image

deployments/k8s/all-in-one-demo.yaml
Created a manifest containing the runtime classes and deployments for sample applications.
=> demo: added an all in one manifest for k8s demos

containerd-shim-slight-v1/quickstart.md, containerd-shim-spin-v1/quickstart.md
updated links in quickstarts for new yaml locations
=> docs:fix quickstart links

containerd-shim-slight-v1/quickstart.md, containerd-shim-spin-v1/quickstart.md
=> docs: update build command to buildx

containerd-shim-spin-v1/Cargo.lock, containerd-shim-spin-v1/Cargo.toml, containerd-shim-spin-v1/src/main.rs
=> chore: updated spin to v0.6.0

images/slight/Cargo.toml, images/spin/Cargo.toml
See #57 for more information about this PR. 
=> strip symbols for spin and slight images

containerd-shim-spin-v1/src/main.rs
This makes ctrl+c work when running this shim with Docker
=> Handle SIGINT too on killing

containerd-shim-slight-v1/src/main.rs, containerd-shim-spin-v1/src/main.rs
This PR fixes #68. 
Signed-off-by: David Justice <david@devigned.com>
=> fix a clippy fmt error

proposals/2022-09-14-kubernetes-versioning.md
- define a strategy for versioning shims, containerd handlers, and RuntimeClasses together into a coherent, safe, and flexible scheme.
=> add proposal for runtimeclass versioning

Cargo.lock, Makefile, containerd-shim-slight-v1/Cargo.lock, containerd-shim-slight-v1/Cargo.toml, containerd-shim-slight-v1/src/main.rs, deployments/k3d/Makefile, deployments/k3d/workload/runtime.yaml, deployments/k3d/workload/workload.yaml, images/slight/Cargo.lock, images/slight/Cargo.toml, images/slight/Dockerfile, images/slight/http-handler.wit, images/slight/http-server-export.wit, images/slight/http-server.wit, images/slight/http-types.wit, images/slight/slightfile.toml, images/slight/src/lib.rs, images/spin/Cargo.lock, tests/integration_test.rs, tests/setup.py, tests/workloads/workload.yaml
- update dependencies and target devigned/spiderlighting#ioredirect to add podio support until https://github.com/deislabs/spiderlightning/pull/342 merges.
=> add slight podio and update deps

containerd-shim-slight-v1/Cargo.lock, containerd-shim-slight-v1/Cargo.toml, containerd-shim-slight-v1/src/main.rs
- Update slight to the v0.5.0 version
- Update wasmtime to v8
=> update slight and wasmtime

README.md
=> fix: update Using a shim in Kubernetes

containerd-shim-wws-v1/Cargo.lock, containerd-shim-wws-v1/Cargo.toml, containerd-shim-wws-v1/src/main.rs
Reference: https://github.com/vmware-labs/wasm-workers-server/releases/tag/v1.4.0
=> feat: bump containerd-shim-wws to use wws v1.4.0

containerd-shim-spin-v1/Cargo.lock, containerd-shim-spin-v1/Cargo.toml
Bumps the spin version to v1.4.0.
=> Bump the Spin Version

containerd-shim-lunatic-v1/Cargo.lock, containerd-shim-lunatic-v1/Cargo.toml, containerd-shim-lunatic-v1/src/main.rs, containerd-shim-slight-v1/Cargo.lock, containerd-shim-slight-v1/Cargo.toml, containerd-shim-slight-v1/src/main.rs, containerd-shim-spin-v1/Cargo.lock, containerd-shim-spin-v1/Cargo.toml, containerd-shim-spin-v1/src/main.rs, containerd-shim-wws-v1/Cargo.lock, containerd-shim-wws-v1/Cargo.toml, containerd-shim-wws-v1/src/main.rs
Remove all the repeated `determine_rootdir` code from all 4 shims :)
=> Chore: update to the newest main branch from `runwasi`

.github/workflows/docker-build-push.yaml, .github/workflows/release.yaml
My attempt to fix the relase pipeline.
=> Fixed the release pipeline

containerd-shim-wws-v1/Cargo.lock, containerd-shim-wws-v1/Cargo.toml
Bump wasm-workers-server to 1.6.1
=> chore: bump wws to 1.6.1

Cargo.toml, containerd-shim-lunatic/Cargo.lock, containerd-shim-lunatic/Cargo.toml, containerd-shim-slight/Cargo.lock, containerd-shim-slight/Cargo.toml, containerd-shim-spin/Cargo.lock, containerd-shim-spin/Cargo.toml, containerd-shim-wws/Cargo.lock, containerd-shim-wws/Cargo.toml, deployments/k3d/README.md, deployments/workloads/workload.yaml, images/slight/Cargo.toml, images/spin-inbound-redis/Cargo.lock, images/spin-inbound-redis/Cargo.toml, images/spin-inbound-redis/Dockerfile, images/spin-inbound-redis/src/lib.rs, images/spin-outbound-redis/Cargo.lock, images/spin-outbound-redis/Cargo.toml, images/spin-outbound-redis/src/lib.rs, images/spin/Cargo.toml
=> chore(all): Bump 0.9.3

Cargo.lock, Makefile, containerd-shim-spin/Cargo.lock, containerd-shim-spin/Cargo.toml, containerd-shim-spin/quickstart.md, containerd-shim-spin/src/engine.rs
=> Add support for pulling Spin OCI images

containerd-shim-spin/Cargo.lock, containerd-shim-spin/Cargo.toml, images/spin-inbound-redis/Cargo.toml, images/spin-outbound-redis/Cargo.toml, images/spin/Cargo.toml
spin 2.0.1 has performance and bug fixes.
=> chore(spin): bump to 2.0.1

containerd-shim-spin/Cargo.toml
=> chore(spin): bump to 2.2.0

README.md
Signed-off-by: tpmccallum tim.mccallum@fermyon.com
=> Quick Copy Editing
