deislabs/containerd-wasm-shims

- .gitignore
- Cargo.lock
- Makefile
- README.md
- containerd-shim-spin-v1/Cargo.toml
- deployments/README.md
- deployments/k3d/Dockerfile
- deployments/k3d/Makefile
- deployments/k3d/README.md
- deployments/k3d/config.toml.tmpl
- deployments/workloads/runtime.yml
- deployments/workloads/workload.yaml
- add static compilation for musl so that we can run it on the k3d base image
- add examples and documentation on how to deploy the shims
- add a deployment mechanism that can be used for multiple shims and K8s workloads
> add k3d cluster deployment example with static musl compile

- .github/workflows/build.yaml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Makefile
- deployments/k3d/Makefile
- reuse build workflow for both ci and release
- add a cross compilation workflow that can be called with input
- add release and build workflow steps to produce the k3d demo image
> dry up build and add release for k3d demo image

- .github/workflows/build.yaml
- .github/workflows/release.yml
- cache build results so they can be used by subsequent jobs in workflows.
> cache build results for subsequent jobs

- .github/workflows/build.yaml
- .github/workflows/release.yml
- fix 'yml' endings for artifacts in the release workflow
- relax the cache key constrain for the build job
> fix release workflow and relax cache key lookup

- deployments/k3d/Makefile
- deployments/k3d/README.md
- deployments/workloads/workload.yaml
- add traefik ingress for the workload
- remove sulfurous `--api-port` flag
- add a couple k3d agents for fun
> fix workload to run with traefik in k3d

- deployments/k3d/README.md
- deployments/workloads/workload.yaml
- removed service type loadbalancer from the example workload as traefik needs ClusterIP to work correctly
> remove service type lb from example workload

- containerd-shim-slight-v1/Cargo.lock
- containerd-shim-slight-v1/Cargo.toml
- containerd-shim-slight-v1/src/main.rs
- deployments/k3d/Makefile
- deployments/workloads/slight/workload.yaml
- images/slight/Cargo.lock
- images/slight/Cargo.toml
- images/slight/Dockerfile
- images/slight/kv.wit
- images/slight/resources.wit
- images/slight/slightfile.toml
- images/slight/src/main.rs
This PR mounts the shim's resolv.conf to host's, so that the shim can use host's nameserver to do dns resolution. A consequence of this PR is that we can use outbound-http in our shim, and thus each http handler can read/write to external services such as AWS DynamoDB.
> feat(slight-shim): mount the shim's resolv.conf to host's

- .github/workflows/build.yaml
- .github/workflows/release.yaml
The build job moved the bins to ./bin. These artifacts are needed in the release build and can only be shared by persisting them across jobs. This PR adds ./bin to the cache path.
> add ./bin to the cache path to be shared between jobs

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- Makefile
- build no longer shares a cache across jobs
- use artifacts to persist build artifacts across jobs
- change make to use cross by default, but also leave existing `make build` tasks
- release no long depends on cache, but rather, uses artifacts produced from the build.yaml
> refactor build to use artifacts

- .devcontainer/devcontainer.json
This PR adds a basic devcontainer configuration that can be used to start a GitHub CodeSpace for containerd-shim testing via the k3d deployment instructions. Users can start a codespace using this configuration and the follow the k3d shim deployment steps to get a running k3d cluster with the shim installed.
> Enable CodeSpaces configuration

- Cargo.lock
- Makefile
- containerd-shim-spin-v1/Cargo.lock
- containerd-shim-spin-v1/Cargo.toml
- containerd-shim-spin-v1/src/main.rs
- tests/integration_test.rs
- update the spin dependencies to v0.7.1
- add support for the Spin trigger [`RUNTIME_CONFIG_FILE` option](https://github.com/fermyon/spin/blob/eb3de4f072f4dfe964d4e2eb564e02b8e1faa012/crates/trigger/src/cli.rs#L84) by looking for the config in a "well known" location `rootfs/runtime_config.toml`.
> update spin deps to v0.7.1

- images/spin/Cargo.lock
- images/spin/Cargo.toml
- images/spin/Dockerfile
- images/spin/go-hello/go.mod
- images/spin/go-hello/go.sum
- images/spin/go-hello/main.go
- images/spin/spin.toml
This PR adds a new go-http component to the existing spin image. It shows that the spin shim can run more than one wasm modules as long as the wasm files are in the same file structure as defined in the spin.toml file. 
> feat: added a go component to spin image

- Cargo.lock
- Cargo.toml
- containerd-shim-slight-v1/Cargo.toml
- containerd-shim-spin-v1/Cargo.toml
@devigned Do we want to follow the runtimeclass and shim binary versioning scheme described in https://github.com/deislabs/containerd-wasm-shims/pull/16?
> Chore: bump version to v0.4.0

- Makefile
- Release artifacts are in sub project directories. When `make install` is run, the artifacts are not found and the copy will fail. This corrects that.
> fix path for release artifacts in make install

- Cargo.lock
- containerd-shim-slight-v1/Cargo.lock
- containerd-shim-slight-v1/Cargo.toml
- containerd-shim-slight-v1/src/main.rs
- containerd-shim-spin-v1/Cargo.lock
- containerd-shim-spin-v1/Cargo.toml
`runwasi` was moved to the containerd namespace, let's use it
> Switch to containerd/runwasi

- containerd-shim-spin-v1/Cargo.lock
- containerd-shim-spin-v1/Cargo.toml
- containerd-shim-spin-v1/src/main.rs
- containerd-shim-spin-v1/src/podio.rs
- images/spin-outbound-redis/Cargo.lock
- images/spin-outbound-redis/Cargo.toml
- images/spin/Cargo.lock
- images/spin/Cargo.toml
Update the dependencies for the Spin shim and the test workloads to `v1.0.0`.
:rocket:  https://github.com/fermyon/spin/releases/tag/v1.0.0 :rocket:
> bump the spin dependencies to v1.0.0

- .dockerignore
The docker build context for the slight shim, if including `target`, is often ~2GB in size. This slows down local development process. This PR adds a `.dockerignore` file to ignore target.
> feat: add dockerignore to reduce build context

- containerd-shim-spin-v1/Cargo.lock
- containerd-shim-spin-v1/Cargo.toml
- containerd-shim-spin-v1/src/main.rs
- containerd-shim-spin-v1/src/podio.rs
This PR is pending https://github.com/fermyon/spin/pull/1433 and as soon as spin's PR to bump to wasmtime 8.0.1 is merged in, it's ready to review.
> chore: bump spin to wasmtime 8.0.1

- deployments/k3d/DockerSetup.md
- deployments/k3d/README.md
This PR adds documentation for setting up Docker+Wasm integration on docker daemon. It largely follows the steps described in #87 . 
@rumpl could you please take a look?
> docs: Add document for setup Docker+Wasm on docker daemon

- containerd-shim-slight-v1/src/main.rs
For JS guest applications (made possible in slight v0.5.0), all capability linkage must be enabled. This is because all capabilities are baked into the SlightJS engine, and so it expects them to be available in Wasmtime. If not, we get this error:
This does not impact applications that don't require all capabilities linked, as those are still added to our capability store later on. All this those is link them in Wasmtime.
> enable all capability linkage

- containerd-shim-wws-v1/Cargo.lock
- containerd-shim-wws-v1/Cargo.toml
- containerd-shim-wws-v1/src/main.rs
Upgrade the containerd-shim-wws to the latest version of `wws`. We introduced a small change that requires to adapt a method call. This version also includes the configuration of the `stderr`, so we don't need to point to a specific commit anymore 😄 
**References:** 
* [Wasm Workers Server v.1.2.0 release](https://github.com/vmware-labs/wasm-workers-server/releases/tag/v1.2.0)
> feat: bump containerd-shim-wws main wws dependency to v1.2.0

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- Makefile
> fix: spin build failed

- containerd-shim-slight-v1/Cargo.lock
- containerd-shim-slight-v1/Cargo.toml
- containerd-shim-spin-v1/Cargo.lock
- containerd-shim-spin-v1/Cargo.toml
- containerd-shim-wws-v1/Cargo.toml
- deployments/k3d/README.md
- deployments/workloads/workload.yaml
- images/slight/Cargo.lock
- images/slight/Cargo.toml
- images/spin-outbound-redis/Cargo.lock
- images/spin-outbound-redis/Cargo.toml
- images/spin/Cargo.lock
- images/spin/Cargo.toml
> chore: bump version to 0.8.0 for all crates, tests, and images

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- .github/workflows/docker-build-push.yaml
- .github/workflows/release.yaml
- Makefile
- deployments/k3d/Makefile
this commit largely removes the redundency of writing each command once for each shim this repo supports. It uses foreach syntax to iterate over each item in the shims variable and execute a command for each one.
This also applies to the CI. This commit adds a new docker-build-push action that builds and pushes the images to ghcr, abstrating the repeated build and push steps into this reusable workflow.
It also adds spin-inbound-redis and spin-outbound-redis images to the release pipeline
> feat: simplify makefiles and CI

- .github/workflows/docker-build-push.yaml
- .github/workflows/release.yaml
Each execution of GH actions starts a workflow that immediately fails. It has no effect on the build itself, but pollutes the workflow list.
This PR renames the secret used in the reusable workflow from `GITHUB_TOKEN` to `envPAT`, since GITHUB_TOKEN is a reserved word.
> fix: pipeline build and push

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
In addition to #126, this PR changes the build workflow to stars one job per shim and architecture. By parallelizing the builds, we get a nearly constant build time even as more shims are added.
> chore: parallel build for shims

- containerd-shim-lunatic-v1/Cargo.lock
- containerd-shim-lunatic-v1/Cargo.toml
- containerd-shim-slight-v1/Cargo.lock
- containerd-shim-slight-v1/Cargo.toml
- containerd-shim-spin-v1/Cargo.lock
- containerd-shim-spin-v1/Cargo.toml
- containerd-shim-wws-v1/Cargo.lock
- containerd-shim-wws-v1/Cargo.toml
- images/spin-outbound-redis/Cargo.toml
- images/spin/Cargo.toml
This commit bumps runwasi and containerd-shim to `v0.5.0` and spin to `v1.4.1`.
> chore: bump dependencies and spin to v1.4.1

- Makefile
- containerd-shim-wws-v1/Cargo.lock
- containerd-shim-wws-v1/Cargo.toml
- containerd-shim-wws-v1/src/executor.rs
- containerd-shim-wws-v1/src/main.rs
> chore: bump WWS to 1.5.0

- containerd-shim-lunatic-v1/build.rs
- containerd-shim-lunatic-v1/src/main.rs
- containerd-shim-slight-v1/build.rs
- containerd-shim-slight-v1/src/main.rs
- containerd-shim-spin-v1/build.rs
- containerd-shim-spin-v1/src/main.rs
- containerd-shim-wws-v1/build.rs
- containerd-shim-wws-v1/src/main.rs
This commit follows https://github.com/containerd/runwasi/pull/268 to add `--version` or `-v` flag to all the shims.
> feat: add -v flag to all shims

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- .github/workflows/docker-build-push.yaml
- .github/workflows/release.yaml
This commit adds a new job to the `build` workflow to verify all the wasm images could be built in Docker. This sets the `push` parameter to false in `build` so that images will not be uploaded.
> CI: add image docker build to the build pipeline

- containerd-shim-lunatic-v1/Cargo.toml
- containerd-shim-slight-v1/Cargo.toml
- containerd-shim-spin-v1/Cargo.toml
- containerd-shim-wws-v1/Cargo.toml
This PR enables the "v1" feature for libcontainer to support K8s distributions such as CoLima and Civo K3s.
fixes: https://github.com/containerd/runwasi/issues/288#issuecomment-1707764979
> fix: add cgroup v1 support

- .github/workflows/release.yaml
- deployments/k3d/Dockerfile
This PR changes the release pipeline to produce K3d images where the binaries match the image architecture.
fixes: #147
> fix: CI for k3d arm64 image

- Cargo.toml
- containerd-shim-lunatic-v1/Cargo.lock
- containerd-shim-slight-v1/Cargo.lock
- containerd-shim-slight-v1/Cargo.toml
- containerd-shim-spin-v1/Cargo.lock
- containerd-shim-spin-v1/Cargo.toml
- containerd-shim-wws-v1/Cargo.lock
- containerd-shim-wws-v1/Cargo.toml
- deployments/k3d/README.md
- deployments/workloads/workload.yaml
- images/slight/Cargo.toml
- images/spin-outbound-redis/Cargo.toml
- images/spin/Cargo.toml
Prepare for the release of `v0.9.1` by #154
> chore: bump version to v0.9.1

- .github/workflows/docker-build-push.yaml
This commits revert #146's change that updated "docker/build-push-action" from `v3` to `v4`. This is because the new images being pushed to ghci don't have Linux/amd64 platforms anymore, which then can't be pulled by Kubernetes. Note that this isn't a long term solution. 
After this PR merges, I will do another release of `v0.9.1`
CC @0xE282B0 @jprendes
> revert docker build-push-action back to v3

- .cargo/config.toml
- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- Cargo.lock
- Makefile
- containerd-shim-spin-v1/Cargo.lock
- containerd-shim-spin-v1/Cargo.toml
- containerd-shim-spin-v1/Cross.toml
- containerd-shim-spin-v1/Dockerfile
- containerd-shim-spin-v1/polyfill/README.md
- containerd-shim-spin-v1/polyfill/polyfill.sh
- containerd-shim-spin-v1/polyfill/polyfill_vld1q_s8_x4.h
- containerd-shim-spin-v1/polyfill/polyfill_vld1q_u8_x4.h
- containerd-shim-spin-v1/polyfill/test_vld1q_s8_x4.c
- containerd-shim-spin-v1/polyfill/test_vld1q_u8_x4.c
- containerd-shim-spin-v1/src/engine.rs
- rust-toolchain.toml
> chore: bump spin version to 1.5.0

- containerd-shim-spin-v1/Cargo.toml
- containerd-shim-spin-v1/src/engine.rs
Add trigger-hook to forward spin module stdout.
@jpflueger, @voigt could you check if it fixes the problem for you as well?
closes #123
> fix: show logs of spin module

- containerd-shim-spin-v1/src/engine.rs
As @jprendes mentioned https://github.com/deislabs/containerd-wasm-shims/pull/168#issuecomment-1777071118, here is the missing line 😅
> Add StdioTriggerHook to spin TriggerExecutorBuilder

- Cargo.lock
- containerd-shim-spin/src/engine.rs
Adds support for Runtime Config in the shim by expecting it to be loaded into the root of a container. This is fairly prescriptive. We may want to support detecting/finding the runtime config in Spin runtime instead of passing it as a flag to the Spin CLI. If we come up with a Spin solution to this, we may need to update the shim to be aligned with whatever approach we choose in Spin. But this unlocks a lot of use cases with the Spin shim now.
To test it app, you can use a runtime config to use a non-default KV store. A build example can be pulled from here (http://ghcr.io/kate-goldenring/keyvalue:latest). It is a Spin 1.x app but should still run on the 2.0 shim. I included a [section with the app contents below](#contents-of-the-spin-app).
The Dockerfile for the app looks like:
```
FROM …
```
> feat(spin): conditionally load runtime config from root

- containerd-shim-slight/quickstart.md
- containerd-shim-spin/quickstart.md
- containerd-shim-wws/quickstart.md
- deployments/chat-workloads/workload.yaml
- deployments/k3d/workload/workload.yaml
- deployments/workloads/workload.yaml
- tests/workloads/workload.yaml
Noticed a deprecation warning around the ingress annotation when running the shim via k3s. (`Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead`)
Updated applicable manifests per https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
> fix(*): replace deprecated ingress annotation

- .github/workflows/docker-build-push.yaml
- .github/workflows/release.yaml
Change the static reference to the docker images in the CI build to be dynamic based upon the current repo so that builds in downstream repos can produce images for testing.
> Enable downstream CI builds

- containerd-shim-spin/quickstart.md
Misc. updates and version bumps
- Bump minimum suggested Spin and Rust versions
- Bump k3d example image version
- Update Spin CLI usage (and spin.toml snippet) per v2.0+
- Use `localhost:12345` as registry endpoint following the initial cluster and registry setup
> docs(shim-spin/quickstart): updates and version bumps

- images/spin-dapr/.dockerignore
- images/spin-dapr/.gitignore
- images/spin-dapr/Cargo.toml
- images/spin-dapr/Dockerfile
- images/spin-dapr/README.md
- images/spin-dapr/deploy.yaml
- images/spin-dapr/spin.toml
- images/spin-dapr/src/lib.rs
This PR adds a simple demo of how a spin application can be triggered by dapr to demonstrate the default executor feature.
Closes #130
> feat: add spin-dapr example

- deployments/k3d/Dockerfile
- Bumps the rancher/k3s base image to [v1.27.8-k3s2](https://github.com/k3s-io/k3s/releases/tag/v1.27.8+k3s2).
The goal is mainly to inherit a v1.7.7+ version of containerd to get the OCI support mentioned in https://github.com/deislabs/containerd-wasm-shims/issues/191#issuecomment-1834436484.  I chose a release still in the 1.27x range for k8s but there are 1.28 versions as well.  Definitely open to suggestions on the actual version to bump to, assuming we're able to bump.
Caveat: I haven't been able to build this image and its dependencies locally -- may need pointers on how to best set up a cross-compilation env (I'm on Mac/Apple Silicon).  I was hoping I could lean on CI or a kind volunteer to help verify this version is working as intended 😅
> chore(k3d/Dockerfile): bump rancher/k3s base image

- containerd-shim-spin/Cargo.lock
- containerd-shim-spin/Cargo.toml
- containerd-shim-spin/src/engine.rs
This PR introduces changes to the spin shim. It adds support for the Fermyon [sqs-trigger](http://github.com/fermyon/spin-trigger-sqs).
This PR is a draft PR, since the [sqs-trigger](http://github.com/fermyon/spin-trigger-sqs) cannot yet be imported to use the [SqsTrigger struct](https://github.com/fermyon/spin-trigger-sqs/blob/fdbe434fb664e022c582fac4ffacbdfd721bbec1/src/main.rs#L38). We have a [PR in flight to resolve this issue](https://github.com/fermyon/spin-trigger-sqs/compare/main...0xE282B0:spin-trigger-sqs:sql-trigger-library). The PR will be updated as soon as the official repo has been updated.
> Add sqs-trigger support to spin shim

- containerd-shim-spin/Cargo.lock
- containerd-shim-spin/Cargo.toml
- containerd-shim-spin/src/engine.rs
depends on https://github.com/fermyon/spin-trigger-sqs/pull/13
This commit updates the Spin dependency to v2.1.0.
> Bump Spin shim to Spin v2.1.0

- .github/workflows/docker-build-push.yaml
Close #205
The containerd image store is required to load wasi/wasm images. For more info about the image store, you can read it [here](https://docs.docker.com/desktop/containerd/#what-is-the-containerd-image-store).
Regarding how to enable the image store in docker, please refer to this [page](https://docs.docker.com/storage/containerd/#enable-containerd-image-store-on-docker-engine).
> ci: enable containerd image store for docker

- .github/workflows/docker-build-push.yaml
#211 
By disabling the provenence, we can build and push OCI image instead of an index.
> ci(image): disable docker provenence
